=== SooryaSRajan/NCP_19301_Eval1/recommendation.dtd
<!ELEMENT recommendations (recommendation)+>
<!ELEMENT recommendation (firstname, lastname, organization, title, relation, phone, email, academic, intellectual, motivation, express, admit_applicant, signature)>
<!ATTLIST recommendation prefix (Dr|Mr|Ms) #REQUIRED>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT relation (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT academic (#PCDATA)>
<!ELEMENT intellectual (#PCDATA)>
<!ELEMENT motivation (#PCDATA)>
<!ELEMENT express (#PCDATA)>
<!ELEMENT admit_applicant (#PCDATA)>
<!ELEMENT signature (#PCDATA)>

=== SooryaSRajan/NCP_19301_Eval1/recommendation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recommendations SYSTEM "recommendation.dtd">
<recommendations>
    
    <recommendation prefix="Dr">
        <firstname>Soorya</firstname>
        <lastname>S</lastname>
        <organization>University of Texas at Dallas</organization>
        <title>Assistant Professor</title>
        <relation>Assistant Professor</relation>
        <phone>9842954321</phone>
        <email>soorya@gmail.com</email>
        <academic>Upper 25%</academic>
        <intellectual>Upper 1 to 2%</intellectual>
        <motivation>No Basis for Judgement</motivation>
        <express>Lower Half</express>
        <admit_applicant>Possibly</admit_applicant>
        <signature>Soorya S</signature>
    </recommendation>

    <recommendation prefix="Mr">
        <firstname>Ajay</firstname>
        <lastname>R</lastname>
        <organization>Amrita School of Engineering</organization>
        <title>Associate Professor</title>
        <relation>Associate Professor</relation>
        <phone>89786756456</phone>
        <email>ajay@gmail.com</email>
        <academic>Upper 10%</academic>
        <intellectual>Upper 25%</intellectual>
        <motivation>Upper 50%</motivation>
        <express>Upper 1 to 2%</express>
        <admit_applicant>Possibly</admit_applicant>
        <signature>Soorya S</signature>
    </recommendation>

</recommendations>
